language: java

jdk:
  - oraclejdk8

branches:
  only:
    - master
    - develop

notifications:
  email:
    recipients:
      - diego.castano.chillaron@alumnos.upm.es

script: mvn verify